---
deployment:
  tasks:
    - export DEPLOYPATH=/home/syntumfz/pay.syntaxasia.digital/
    - /usr/bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' --exclude='.env' --exclude='.env.production' --exclude='.htaccess' --exclude='.well-known/' --exclude='.venv' --exclude='tmp/' --exclude='db.sqlite3' --exclude='media/' --exclude='salary_uploads/' --exclude='logs/' ./ $DEPLOYPATH
