# Generated by Django 5.1.4 on 2026-05-24 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Branch name')),
                ('location', models.CharField(blank=True, help_text='Optional: city, address, or region.', max_length=200, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category name')),
                ('description', models.TextField(blank=True, help_text='Optional: describe what type of employees belong here.', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employee category',
                'verbose_name_plural': 'Employee categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(db_index=True, help_text='Must match the employee number used in Excel payroll files.', max_length=20, unique=True, verbose_name='Employee number')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('email', models.EmailField(help_text='Used as the login username. Must be a working email address.', max_length=254, unique=True, verbose_name='Email address')),
                ('date_of_joining', models.DateField(verbose_name='Date of joining')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank name')),
                ('bank_account_name', models.CharField(max_length=150, verbose_name='Bank account name')),
                ('bank_branch_name', models.CharField(max_length=100, verbose_name='Bank branch name')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of deleting. Deactivated employees cannot log in but their payslip history is preserved.', verbose_name='Active')),
                ('must_change_password', models.BooleanField(default=True, help_text='Set automatically when an account is created. Cleared when the employee successfully changes their initial password.', verbose_name='Must change password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.branch', verbose_name='Branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='User account')),
                ('category', models.ForeignKey(blank=True, help_text='Determines which salary structure applies. Changing this does not affect historical paysheets.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.employeecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='emp_active_category_idx'), models.Index(fields=['branch'], name='emp_branch_idx')],
            },
        ),
    ]
