# Generated by Django 3.2.25 on 2026-06-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='company_name',
            field=models.CharField(default='Syntax Asia', max_length=120, verbose_name='Company name'),
        ),
    ]
