# Generated by Django 3.2.25 on 2026-06-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_companysetting_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companysetting",
            name="company_name",
        ),
    ]
