# Generated by Django 5.1.4 on 2026-05-24 18:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original filename')),
                ('file_path', models.CharField(help_text='Path relative to SALARY_UPLOADS_ROOT. Not web-accessible.', max_length=500, verbose_name='Stored file path')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('records_created', models.PositiveIntegerField(default=0, verbose_name='Records created')),
                ('records_updated', models.PositiveIntegerField(default=0, verbose_name='Records updated')),
                ('records_skipped', models.PositiveIntegerField(default=0, verbose_name='Records skipped')),
                ('warnings', models.JSONField(default=list, help_text='List of warning messages from the upload process.', verbose_name='Warnings')),
                ('processing_log', models.TextField(blank=True, verbose_name='Processing log')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='employees.employeecategory', verbose_name='Target category')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_batches', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Upload batch',
                'verbose_name_plural': 'Upload batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaySheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Month')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('breakdown', models.JSONField(default=dict, help_text='JSON object mapping component names to amounts. Example: {"Basic Salary": "50000.00", "HRA": "5000.00"}', verbose_name='Salary breakdown')),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gross total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_snapshot', models.ForeignKey(help_text="Records the employee's category when this paysheet was created. Unaffected by future category changes.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paysheets', to='employees.employeecategory', verbose_name='Category at time of upload')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paysheets', to='employees.employee', verbose_name='Employee')),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paysheets', to='payroll.uploadbatch', verbose_name='Upload batch')),
            ],
            options={
                'verbose_name': 'Pay sheet',
                'verbose_name_plural': 'Pay sheets',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, help_text="Populated if status is 'failed'.", verbose_name='Error message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('batch_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Batch sent at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='employees.employee', verbose_name='Employee')),
                ('paysheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='payroll.paysheet', verbose_name='Pay sheet')),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email logs',
                'ordering': ['-batch_sent_at', 'employee__full_name'],
                'indexes': [models.Index(fields=['paysheet'], name='emaillog_paysheet_idx'), models.Index(fields=['status', 'batch_sent_at'], name='emaillog_status_batch_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['month', 'year', 'category'], name='batch_month_year_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='paysheet',
            index=models.Index(fields=['employee', 'month', 'year'], name='paysheet_emp_month_year_idx'),
        ),
        migrations.AddIndex(
            model_name='paysheet',
            index=models.Index(fields=['month', 'year', 'category_snapshot'], name='paysheet_month_year_cat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paysheet',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
