# Generated by Django 5.1.4 on 2026-05-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryParserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id_row_label', models.CharField(default='Employee', help_text='Text in column A that identifies the employee number row.', max_length=100, verbose_name='Employee ID row label')),
                ('fixed_info_row_labels', models.JSONField(blank=True, default=list, help_text='JSON list of non-salary rows to skip during parsing.', verbose_name='Fixed information row labels')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parser_config', to='employees.employeecategory', verbose_name='Employee category')),
            ],
            options={
                'verbose_name': 'Category parser configuration',
                'verbose_name_plural': 'Category parser configurations',
            },
        ),
    ]
