# Generated by Django 5.1.4 on 2026-05-30 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0002_categoryparserconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryparserconfig',
            options={'verbose_name': 'Category parser config', 'verbose_name_plural': 'Category parser configs'},
        ),
        migrations.AlterField(
            model_name='categoryparserconfig',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parser_config', to='employees.employeecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categoryparserconfig',
            name='emp_id_row_label',
            field=models.CharField(default='Employee', help_text='The exact label in column A that identifies the row containing employee numbers. Case-insensitive match. Example: "Employee", "Emp No.", "Staff ID"', max_length=200, verbose_name='Employee ID row label'),
        ),
        migrations.AlterField(
            model_name='categoryparserconfig',
            name='fixed_info_row_labels',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of row labels to skip - these are informational rows, not salary components. Example: ["Employee Name", "Designation", "Department"]', verbose_name='Fixed info row labels'),
        ),
        migrations.AlterField(
            model_name='categoryparserconfig',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional: describe the expected sheet format for this category.', verbose_name='Notes'),
        ),
    ]
